export const fetchExchangeRates = async (baseCurrency: string = 'USD') => {
  try {
    const response = await fetch(`https://open.er-api.com/v6/latest/${baseCurrency}`);
    if (!response.ok) throw new Error('Failed to fetch rates');
    const data = await response.json();
    return data.rates as Record<string, number>;
  } catch (error) {
    console.error('Error fetching exchange rates:', error);
    return null;
  }
};

export const CURRENCIES = [
  { code: 'ILS', name: 'ישראל - שקל חדש', countryCode: 'il' },
  { code: 'USD', name: 'ארה"ב - דולר', countryCode: 'us' },
  { code: 'EUR', name: 'אירופה - אירו', countryCode: 'eu' },
  { code: 'GBP', name: 'בריטניה - לירה שטרלינג', countryCode: 'gb' },
  { code: 'THB', name: 'תאילנד - בהט', countryCode: 'th' },
  { code: 'JPY', name: 'יפן - ין', countryCode: 'jp' },
  { code: 'AED', name: 'איחוד האמירויות - דירהם', countryCode: 'ae' },
  { code: 'AFN', name: 'אפגניסטן - אפגני', countryCode: 'af' },
  { code: 'ALL', name: 'אלבניה - לק', countryCode: 'al' },
  { code: 'AMD', name: 'ארמניה - דראם', countryCode: 'am' },
  { code: 'ANG', name: 'האנטילים ההולנדיים - גילדן', countryCode: 'cw' },
  { code: 'AOA', name: 'אנגולה - קוואנזה', countryCode: 'ao' },
  { code: 'ARS', name: 'ארגנטינה - פזו', countryCode: 'ar' },
  { code: 'AUD', name: 'אוסטרליה - דולר', countryCode: 'au' },
  { code: 'AWG', name: 'ארובה - פלורין', countryCode: 'aw' },
  { code: 'AZN', name: 'אזרבייג\'ן - מנאט', countryCode: 'az' },
  { code: 'BAM', name: 'בוסניה והרצגובינה - מארק', countryCode: 'ba' },
  { code: 'BBD', name: 'ברבדוס - דולר', countryCode: 'bb' },
  { code: 'BDT', name: 'בנגלדש - טאקה', countryCode: 'bd' },
  { code: 'BGN', name: 'בולגריה - לב', countryCode: 'bg' },
  { code: 'BHD', name: 'בחריין - דינר', countryCode: 'bh' },
  { code: 'BIF', name: 'בורונדי - פרנק', countryCode: 'bi' },
  { code: 'BMD', name: 'ברמודה - דולר', countryCode: 'bm' },
  { code: 'BND', name: 'ברוניי - דולר', countryCode: 'bn' },
  { code: 'BOB', name: 'בוליביה - בוליביאנו', countryCode: 'bo' },
  { code: 'BRL', name: 'ברזיל - ריאל', countryCode: 'br' },
  { code: 'BSD', name: 'איי בהאמה - דולר', countryCode: 'bs' },
  { code: 'BTN', name: 'בהוטן - נגולטרום', countryCode: 'bt' },
  { code: 'BWP', name: 'בוטסואנה - פולה', countryCode: 'bw' },
  { code: 'BYN', name: 'בלארוס - רובל', countryCode: 'by' },
  { code: 'BZD', name: 'בליז - דולר', countryCode: 'bz' },
  { code: 'CAD', name: 'קנדה - דולר', countryCode: 'ca' },
  { code: 'CDF', name: 'הרפובליקה הדמוקרטית של קונגו - פרנק', countryCode: 'cd' },
  { code: 'CHF', name: 'שוויץ - פרנק', countryCode: 'ch' },
  { code: 'CLP', name: 'צ\'ילה - פזו', countryCode: 'cl' },
  { code: 'CNY', name: 'סין - יואן', countryCode: 'cn' },
  { code: 'COP', name: 'קולומביה - פזו', countryCode: 'co' },
  { code: 'CRC', name: 'קוסטה ריקה - קולון', countryCode: 'cr' },
  { code: 'CUP', name: 'קובה - פזו', countryCode: 'cu' },
  { code: 'CVE', name: 'כף ורדה - אסקודו', countryCode: 'cv' },
  { code: 'CZK', name: 'צ\'כיה - קורונה', countryCode: 'cz' },
  { code: 'DJF', name: 'ג\'יבוטי - פרנק', countryCode: 'dj' },
  { code: 'DKK', name: 'דנמרק - קרונה', countryCode: 'dk' },
  { code: 'DOP', name: 'הרפובליקה הדומיניקנית - פזו', countryCode: 'do' },
  { code: 'DZD', name: 'אלג\'יריה - דינר', countryCode: 'dz' },
  { code: 'EGP', name: 'מצרים - לירה', countryCode: 'eg' },
  { code: 'ERN', name: 'אריתריאה - נאקפה', countryCode: 'er' },
  { code: 'ETB', name: 'אתיופיה - ביר', countryCode: 'et' },
  { code: 'FJD', name: 'פיג\'י - דולר', countryCode: 'fj' },
  { code: 'FKP', name: 'איי פוקלנד - לירה', countryCode: 'fk' },
  { code: 'FOK', name: 'איי פארו - קרונה', countryCode: 'fo' },
  { code: 'GEL', name: 'גיאורגיה - לארי', countryCode: 'ge' },
  { code: 'GGP', name: 'גרנזי - לירה', countryCode: 'gg' },
  { code: 'GHS', name: 'גאנה - סדי', countryCode: 'gh' },
  { code: 'GIP', name: 'גיברלטר - לירה', countryCode: 'gi' },
  { code: 'GMD', name: 'גמביה - דלאסי', countryCode: 'gm' },
  { code: 'GNF', name: 'גינאה - פרנק', countryCode: 'gn' },
  { code: 'GTQ', name: 'גואטמלה - קצאל', countryCode: 'gt' },
  { code: 'GYD', name: 'גיאנה - דולר', countryCode: 'gy' },
  { code: 'HKD', name: 'הונג קונג - דולר', countryCode: 'hk' },
  { code: 'HNL', name: 'הונדורס - למפירה', countryCode: 'hn' },
  { code: 'HRK', name: 'קרואטיה - קונה', countryCode: 'hr' },
  { code: 'HTG', name: 'האיטי - גורד', countryCode: 'ht' },
  { code: 'HUF', name: 'הונגריה - פורינט', countryCode: 'hu' },
  { code: 'IDR', name: 'אינדונזיה - רופיה', countryCode: 'id' },
  { code: 'IMP', name: 'האי מאן - לירה', countryCode: 'im' },
  { code: 'INR', name: 'הודו - רופי', countryCode: 'in' },
  { code: 'IQD', name: 'עיראק - דינר', countryCode: 'iq' },
  { code: 'IRR', name: 'איראן - ריאל', countryCode: 'ir' },
  { code: 'ISK', name: 'איסלנד - קרונה', countryCode: 'is' },
  { code: 'JEP', name: 'ג\'רזי - לירה', countryCode: 'je' },
  { code: 'JMD', name: 'ג\'מייקה - דולר', countryCode: 'jm' },
  { code: 'JOD', name: 'ירדן - דינר', countryCode: 'jo' },
  { code: 'KES', name: 'קניה - שילינג', countryCode: 'ke' },
  { code: 'KGS', name: 'קירגיזסטן - סום', countryCode: 'kg' },
  { code: 'KHR', name: 'קמבודיה - ריל', countryCode: 'kh' },
  { code: 'KID', name: 'קיריבטי - דולר', countryCode: 'ki' },
  { code: 'KMF', name: 'קומורו - פרנק', countryCode: 'km' },
  { code: 'KRW', name: 'דרום קוריאה - וון', countryCode: 'kr' },
  { code: 'KWD', name: 'כווית - דינר', countryCode: 'kw' },
  { code: 'KYD', name: 'איי קיימן - דולר', countryCode: 'ky' },
  { code: 'KZT', name: 'קזחסטן - טנגה', countryCode: 'kz' },
  { code: 'LAK', name: 'לאוס - קיפ', countryCode: 'la' },
  { code: 'LBP', name: 'לבנון - לירה', countryCode: 'lb' },
  { code: 'LKR', name: 'סרי לנקה - רופי', countryCode: 'lk' },
  { code: 'LRD', name: 'ליבריה - דולר', countryCode: 'lr' },
  { code: 'LSL', name: 'לסוטו - לוטי', countryCode: 'ls' },
  { code: 'LYD', name: 'לוב - דינר', countryCode: 'ly' },
  { code: 'MAD', name: 'מרוקו - דירהם', countryCode: 'ma' },
  { code: 'MDL', name: 'מולדובה - לאו', countryCode: 'md' },
  { code: 'MGA', name: 'מדגסקר - אריארי', countryCode: 'mg' },
  { code: 'MKD', name: 'מקדוניה - דינר', countryCode: 'mk' },
  { code: 'MMK', name: 'מיאנמר - צ\'אט', countryCode: 'mm' },
  { code: 'MNT', name: 'מונגוליה - טוגרוג', countryCode: 'mn' },
  { code: 'MOP', name: 'מקאו - פטקה', countryCode: 'mo' },
  { code: 'MRU', name: 'מאוריטניה - אוגויה', countryCode: 'mr' },
  { code: 'MUR', name: 'מאוריציוס - רופי', countryCode: 'mu' },
  { code: 'MVR', name: 'מלדיביים - רופיה', countryCode: 'mv' },
  { code: 'MWK', name: 'מלאווי - קוואצ\'ה', countryCode: 'mw' },
  { code: 'MXN', name: 'מקסיקו - פזו', countryCode: 'mx' },
  { code: 'MYR', name: 'מלזיה - רינגיט', countryCode: 'my' },
  { code: 'MZN', name: 'מוזמביק - מטיקל', countryCode: 'mz' },
  { code: 'NAD', name: 'נמיביה - דולר', countryCode: 'na' },
  { code: 'NGN', name: 'ניגריה - נאירה', countryCode: 'ng' },
  { code: 'NIO', name: 'ניקרגואה - קורדובה', countryCode: 'ni' },
  { code: 'NOK', name: 'נורווגיה - קרונה', countryCode: 'no' },
  { code: 'NPR', name: 'נפאל - רופי', countryCode: 'np' },
  { code: 'NZD', name: 'ניו זילנד - דולר', countryCode: 'nz' },
  { code: 'OMR', name: 'עומאן - ריאל', countryCode: 'om' },
  { code: 'PAB', name: 'פנמה - בלבואה', countryCode: 'pa' },
  { code: 'PEN', name: 'פרו - סול', countryCode: 'pe' },
  { code: 'PGK', name: 'פפואה גינאה החדשה - קינה', countryCode: 'pg' },
  { code: 'PHP', name: 'פיליפינים - פזו', countryCode: 'ph' },
  { code: 'PKR', name: 'פקיסטן - רופי', countryCode: 'pk' },
  { code: 'PLN', name: 'פולין - זלוטי', countryCode: 'pl' },
  { code: 'PYG', name: 'פרגוואי - גוארני', countryCode: 'py' },
  { code: 'QAR', name: 'קטאר - ריאל', countryCode: 'qa' },
  { code: 'RON', name: 'רומניה - לאו', countryCode: 'ro' },
  { code: 'RSD', name: 'סרביה - דינר', countryCode: 'rs' },
  { code: 'RUB', name: 'רוסיה - רובל', countryCode: 'ru' },
  { code: 'RWF', name: 'רואנדה - פרנק', countryCode: 'rw' },
  { code: 'SAR', name: 'ערב הסעודית - ריאל', countryCode: 'sa' },
  { code: 'SBD', name: 'איי שלמה - דולר', countryCode: 'sb' },
  { code: 'SCR', name: 'סיישל - רופי', countryCode: 'sc' },
  { code: 'SDG', name: 'סודאן - לירה', countryCode: 'sd' },
  { code: 'SEK', name: 'שוודיה - קרונה', countryCode: 'se' },
  { code: 'SGD', name: 'סינגפור - דולר', countryCode: 'sg' },
  { code: 'SHP', name: 'סנט הלנה - לירה', countryCode: 'sh' },
  { code: 'SLE', name: 'סיירה לאון - ליאון', countryCode: 'sl' },
  { code: 'SOS', name: 'סומליה - שילינג', countryCode: 'so' },
  { code: 'SRD', name: 'סורינאם - דולר', countryCode: 'sr' },
  { code: 'SSP', name: 'דרום סודאן - לירה', countryCode: 'ss' },
  { code: 'STN', name: 'סאו טומה ופרינסיפה - דוברה', countryCode: 'st' },
  { code: 'SYP', name: 'סוריה - לירה', countryCode: 'sy' },
  { code: 'SZL', name: 'אסוואטיני - לילנגני', countryCode: 'sz' },
  { code: 'THB', name: 'תאילנד - בהט', countryCode: 'th' },
  { code: 'TJS', name: 'טג\'יקיסטן - סומוני', countryCode: 'tj' },
  { code: 'TMT', name: 'טורקמניסטן - מנאט', countryCode: 'tm' },
  { code: 'TND', name: 'תוניסיה - דינר', countryCode: 'tn' },
  { code: 'TOP', name: 'טונגה - פאנגה', countryCode: 'to' },
  { code: 'TRY', name: 'טורקיה - לירה', countryCode: 'tr' },
  { code: 'TTD', name: 'טרינידד וטובגו - דולר', countryCode: 'tt' },
  { code: 'TVD', name: 'טובאלו - דולר', countryCode: 'tv' },
  { code: 'TWD', name: 'טאיוואן - דולר', countryCode: 'tw' },
  { code: 'TZS', name: 'טנזניה - שילינג', countryCode: 'tz' },
  { code: 'UAH', name: 'אוקראינה - הריבניה', countryCode: 'ua' },
  { code: 'UGX', name: 'אוגנדה - שילינג', countryCode: 'ug' },
  { code: 'UYU', name: 'אורוגוואי - פזו', countryCode: 'uy' },
  { code: 'UZS', name: 'אוזבקיסטן - סום', countryCode: 'uz' },
  { code: 'VES', name: 'ונצואלה - בוליבר', countryCode: 've' },
  { code: 'VND', name: 'וייטנאם - דונג', countryCode: 'vn' },
  { code: 'VUV', name: 'ונואטו - ואטו', countryCode: 'vu' },
  { code: 'WST', name: 'סמואה - טאלה', countryCode: 'ws' },
  { code: 'XAF', name: 'מרכז אפריקה - פרנק', countryCode: 'cm' },
  { code: 'XCD', name: 'מזרח הקריביים - דולר', countryCode: 'ag' },
  { code: 'XOF', name: 'מערב אפריקה - פרנק', countryCode: 'sn' },
  { code: 'XPF', name: 'פולינזיה הצרפתית - פרנק', countryCode: 'pf' },
  { code: 'YER', name: 'תימן - ריאל', countryCode: 'ye' },
  { code: 'ZAR', name: 'דרום אפריקה - ראנד', countryCode: 'za' },
  { code: 'ZMW', name: 'זמביה - קוואצ\'ה', countryCode: 'zm' },
  { code: 'ZWL', name: 'זימבבואה - דולר', countryCode: 'zw' },
].sort((a, b) => a.name.localeCompare(b.name, 'he'));

export const formatAmount = (amount: number): string => {
  if (amount % 1 === 0) {
    return amount.toFixed(0);
  }
  return amount.toFixed(2);
};
